apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.configmap | nindent 6 }}